# fly.toml file generated for surrealfly on 2022-12-21T23:16:46-05:00

app = "surrealfly"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  USER = "root"
  LOG = "debug"
  DB_PATH = "file:///surrealfly_data"
  BIND = "0.0.0.0:8080"
  
[mounts]
source = "surrealfly_data"
destination = "/surrealfly_data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
